spring:
  config:
    activate:
      on-profile: "qa"
# Property to be read from code
build:
  version: "v4.0"

#@ConfigurationProperties
contact:
  message: "Bank System - CARDS API QA"
  details:
    name: "Lorena Botia - Developer Master QA"
    email: "lore23@gmail.com"
  phone-numbers:
    - "(57) 305-745-8888"
    - "(57) 305-261-0777"